--Explore the DB Structure
SELECT * FROM INFORMATION_SCHEMA.TABLES
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME ='dim_customers'
--===================================================
--Explore Dimension values
--===================================================
SELECT DISTINCT country FROM gold.dim_customers
/*n/a
Germany
United States
Australia
United Kingdom
Canada
France*/
SELECT DISTINCT category FROM gold.dim_products
/*NULL
Accessories
Bikes
Clothing
Components*/
SELECT DISTINCT category,subcategory FROM gold.dim_products
/*NULL	NULL
Accessories	Bike Racks
Accessories	Bike Stands
Accessories	Bottles and Cages
Accessories	Cleaners
Accessories	Fenders
Accessories	Helmets
Accessories	Hydration Packs
Accessories	Lights
Accessories	Locks
Accessories	Panniers
Accessories	Pumps
Accessories	Tires and Tubes
Bikes	Mountain Bikes
Bikes	Road Bikes
Bikes	Touring Bikes
Clothing	Bib-Shorts
Clothing	Caps
Clothing	Gloves
Clothing	Jerseys
Clothing	Shorts
Clothing	Socks
Clothing	Tights
Clothing	Vests
Components	Bottom Brackets
Components	Brakes
Components	Chains
Components	Cranksets
Components	Derailleurs
Components	Forks
Components	Handlebars
Components	Headsets
Components	Mountain Frames
Components	Road Frames
Components	Saddles
Components	Touring Frames
Components	Wheels*/
SELECT DISTINCT category,subcategory,product_name FROM gold.dim_products
--around 300 row(300 different product_name)

--Date Exploration
SELECT 
	MIN(order_date) AS first_order_date,
	Max (order_date) AS last_order_date
FROM gold.fact_sales
--2010-12-29	2014-01-28
SELECT 
	DATEDIFF(month, MIN(order_date),Max (order_date) ) AS order_range_months,
	DATEDIFF(YEAR, MIN(order_date),Max (order_date) ) AS order_range_years
FROM gold.fact_sales
--37months	4years
SELECT 
	MIN(birth_date) AS oldest_birthday,
	MAX(birth_date) AS youngest_birthday
FROM gold.dim_customers
--1916-02-10	1986-06-25
SELECT 
	DATEDIFF (YEAR, MIN(birth_date),GETDATE()) AS oldest_age,
	DATEDIFF (YEAR, MAX(birth_date),GETDATE()) AS youngest_age
FROM gold.dim_customers
--110	40

--=======================================================
-- Measure Exploration
--=======================================================
-- Generate a Report that shows all key metrics of the business

SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'Average Price', AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Orders', COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Products', COUNT(product_name) FROM gold.dim_products
UNION ALL
SELECT 'Total Nr. Customers', COUNT(customer_key) FROM gold.dim_customers
/*Total Sales	29356250
Total Quantity	60423
Average Price	486
Total Nr. Orders	27659
Total Nr. Products	295
Total Nr. Customers	18484*/


--Magnitude :Nmber of (Measure) in (Dimension)
-- Find total customers by countries
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC
/*United States	7482
Australia	3591
United Kingdom	1913
France	1810
Germany	1780
Canada	1571
n/a	337*/

-- Find total customers by gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC
/*Male	9341
Female	9128
n/a	15*/
-- Find total products by category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;
/*Components	127
Bikes	97
Clothing	35
Accessories	29
NULL	7*/
-- What is the average costs in each category?
SELECT
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;
/*Bikes	949
Components	264
NULL	28
Clothing	24
Accessories	13*/
-- What is the total revenue generated for each category?
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;
/*Bikes	28316272
Accessories	700262
Clothing	339716*/

-- Find total revenue generated by each customer
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON f.customer_key = c.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;
---- Find total revenue generated by each country
SELECT
    c.country,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON f.customer_key = c.customer_key
GROUP BY 
    c.country
ORDER BY total_revenue DESC;
/*United States	9162327
Australia	9060172
United Kingdom	3391376
Germany	2894066
France	2643751
Canada	1977738
n/a	226820*/
---- What is the distribution of sold items across countries
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON f.customer_key = c.customer_key
GROUP BY 
    c.country
ORDER BY total_sold_items DESC;
/*United States	20481
Australia	13346
Canada	7630
United Kingdom	6910
Germany	5626
France	5559
n/a	871*/
--distribution by country and category
SELECT
    c.country,
    p.category,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON f.customer_key = c.customer_key
LEFT JOIN gold.dim_products p
    ON f.product_key = p.product_key
GROUP BY 
    c.country,
    p.category
ORDER BY total_sold_items DESC;
/*United States	Accessories	12527
Australia	Accessories	7005
Canada	Accessories	5374
United States	Bikes	4745
Australia	Bikes	4472
United Kingdom	Accessories	4061
France	Accessories	3345
Germany	Accessories	3273
United States	Clothing	3209
Australia	Clothing	1869
United Kingdom	Bikes	1858
Germany	Bikes	1600
France	Bikes	1444
Canada	Clothing	1332
United Kingdom	Clothing	991
Canada	Bikes	924
France	Clothing	770
Germany	Clothing	753
n/a	Accessories	527
n/a	Clothing	182
n/a	Bikes	162*/

--=============================================
--Ranking Analyzes
--=============================================
-- Which 5 products generate the highest revenue?
SELECT TOP 5
    p.product_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC;
/*Mountain-200 Black- 46	1373454
Mountain-200 Black- 42	1363128
Mountain-200 Silver- 38	1339394
Mountain-200 Silver- 46	1301029
Mountain-200 Black- 38	1294854*/
-- What are the 5 worst-performing products in terms of sales?
SELECT TOP 5
    p.product_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC;
/*Racing Socks- L	2430
Racing Socks- M	2682
Patch Kit/8 Patches	6382
Bike Wash - Dissolver	7272
Touring Tire Tube	7440*/
--or u can use the RANK functions where its more complex 